spring.application.name=student

#------------------database config--------------------
spring.datasource.url=jdbc:mysql://localhost:3306/std_management
spring.datasource.username=your_username
spring.datasource.password=your_password

#--------------JPA/HIBERNET config---------------------------
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
