spring.application.name=student

#------------------database config--------------------
spring.datasource.url=jdbc:mysql://localhost:3306/std_management
spring.datasource.username=root
spring.datasource.password=krishnaa@123

#--------------JPA/HIBERNET config---------------------------
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true